Repository souleimaneelqodsi/eventura, pull requests merged in 2025-04, with the labels that each got.

#36 Error fix in Sign up view and service
  lib/core/services/auth_service.dart
  lib/ui/views/auth/signup_view.dart
Labels: bug

#33 home page view
  lib/main.dart
  lib/ui/views/create_event_view.dart
  lib/ui/views/events_list_view.dart
  lib/ui/views/homepage_view.dart
  pubspec.yaml
Labels: enhancement

#48 fix: .gitignore improvement
  .gitignore
Labels: bug-fix

#25 Implémentation du système d'amis : FriendService, FriendsViewmodel, F…
  analysis_options.yaml
  devtools_options.yaml
  lib/core/models/friends.dart
  lib/core/services/auth_service.dart
  lib/core/services/event_service.dart
  lib/core/services/friend_service.dart
  lib/core/viewmodels/auth/login_viewmodel.dart
  lib/core/viewmodels/auth/reset_password_viewmodel.dart
  lib/core/viewmodels/base_viewmodel.dart
  lib/core/viewmodels/event_viewmodel.dart
  lib/core/viewmodels/events_list_viewmodel.dart
  lib/core/viewmodels/friends_viewmodel.dart
  lib/core/viewmodels/homepage_viewmodel.dart
  lib/main.dart
  lib/providers.dart
  lib/ui/views/auth/login_view.dart
  lib/ui/views/auth/reset_password_view.dart
  lib/ui/views/auth/signup_view.dart
  lib/ui/views/create_event_view.dart
  lib/ui/views/event_detail_view.dart
  lib/ui/views/events_list_view.dart
  lib/ui/views/friends_view.dart
  lib/ui/views/homepage_view.dart
  lib/ui/widgets/event_card.dart
  test/auth_service_test.dart
  test/friend_service_test.dart
  test/friend_service_test.mocks.dart
Labels: enhancement, priority

#46 Ajout de la vue profil avec logique Supabase
  lib/core/models/user.dart
  lib/core/services/auth_service.dart
  lib/core/services/friend_service.dart
  lib/core/viewmodels/friends_viewmodel.dart
  lib/core/viewmodels/profile_viewmodel.dart
  lib/main.dart
  lib/providers.dart
  lib/ui/shared/is_editing_profile.dart
  lib/ui/static/about_us.dart
  lib/ui/static/coming_soon.dart
  lib/ui/static/contact_us.dart
  lib/ui/static/faq.dart
  lib/ui/views/auth/signup_view.dart
  lib/ui/views/friends_view.dart
  lib/ui/views/homepage_view.dart
  lib/ui/views/messages_view.dart
  lib/ui/views/profile_view.dart
  lib/ui/views/settings_view.dart
  lib/ui/widgets/auth_wrapper.dart
  pubspec.lock
  pubspec.yaml
  test/auth_service_test.dart
  test/friend_service_test.dart
  test/friend_service_test.mocks.dart
Labels: enhancement, priority

#67 Added reset password and sign out buttons + other minor improvements.
  lib/core/viewmodels/auth/login_viewmodel.dart
  lib/core/viewmodels/profile_viewmodel.dart
  lib/ui/views/auth/login_view.dart
  lib/ui/views/auth/signup_view.dart
  lib/ui/views/event_detail_view.dart
  lib/ui/views/friends_view.dart
  lib/ui/views/profile_view.dart
Labels: enhancement, priority

#68 Feature/settings clean
  .gitignore
  .metadata
  analysis_options.yaml
  lib/core/models/settings.dart
  lib/core/services/auth_service.dart
  lib/core/services/friend_service.dart
  lib/core/services/settings_service.dart
  lib/core/viewmodels/events_list_viewmodel.dart
  lib/core/viewmodels/settings_viewmodel.dart
  lib/main.dart
  lib/providers.dart
  lib/ui/shared/app_colors.dart
  lib/ui/shared/app_theme.dart
  lib/ui/views/auth/login_view.dart
  lib/ui/views/auth/reset_password_view.dart
  lib/ui/views/auth/signup_view.dart
  lib/ui/views/create_event_view.dart
  lib/ui/views/event_detail_view.dart
  lib/ui/views/events_list_view.dart
  lib/ui/views/friends_view.dart
  lib/ui/views/homepage_view.dart
  lib/ui/views/messages_view.dart
  lib/ui/views/profile_view.dart
  lib/ui/views/settings_view.dart
  lib/ui/widgets/auth_wrapper.dart
  lib/ui/widgets/custom_button.dart
  lib/ui/widgets/destructive_button.dart
  lib/ui/widgets/event_card.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement, priority

#76 Changed the icon for deleting a friend from the friends view list + made bottom error message in login view red
  lib/ui/views/auth/login_view.dart
  lib/ui/views/friends_view.dart
Labels: enhancement
